- name: Installing maven and java 17
  ansible.builtin.import_role_role:
    name: command
    tasks_from: maven-java


- name: Setup application
  ansible.builtin.import_role_role:
    name: common
    tasks_from: app-setup

- name: install dependencies
  ansible.builtin.command:
    cmd: mvn clean package
    chdir: /app

- name: Rename file using command module
  ansible.builtin.command:
    cmd: mv /app/target/shipping-1.0.jar shipping.jar
    chdir: /app

- name: Daemon reload and start
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-setup