- name: install nginx
  ansible.builtin.yum:
    name: nginx
    state: present

- name: Remove a singdefault html file
  ansible.builtin.file:
    path: /usr/share/nginx/html/*
    state: absent
- name: Download frontend content


  ansible.builtin.get_url:
    url: https://roboshop-builds.s3.amazonaws.com/web.zip
    dest: /tmp

- name: Unzip the Downloaded artifact
  ansible.builtin.unarchive:
    src: /tmp/web.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: setup reverse proxy connection
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf
  notify:
  - restart nginx



- name: network connect
  ansible.builtin.command:  sudo setsebool -P httpd_can_network_connect 1