- name: Install mysql
  ansible.builtin.yum:
    name: mysql
    state: present


- name: Load {{component}} database schema
  ansible.builtin.shell:
    cmd: mysql -h mysql.roboshopservice.store -uroot -pRoboShop@1 < /app/db/schema.sql

- name: Load {{component}} database schema
  ansible.builtin.shell:
    cmd: mysql -h mysql.roboshopservice.store -uroot -pRoboShop@1 < /app/db/app-user.sql

- name: Load {{component}} master data
  ansible.builtin.shell:
    cmd: mysql -h mysql.roboshopservice.store -uroot -pRoboShop@1 < /app/db/master-data.sql

- name: Restart {{component}} service
  ansible.builtin.service:
    name: "{{component}}"
    state: restarted