- name: Install nodejs
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs-setup

- name: Setup application
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: installing dependencies under /app directory
  ansible.builtin.command: 
    cmd: npm install
    chdir: /app


- name: Daemon reload and start
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-setup